config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'chatrooms#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: { case_sensitive: false },
    length: { minimum: 3, maximum: 12 }
  has_many :messages

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:error] = "You must be logged in to perform this action"
            redirect_to login_path
        end
    end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController

  def index
    @messages = Message.all.order(created_at: :asc)
    @users = User.all.order('LOWER(username)')
    @message = Message.new
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user
  
  def create
    message = current_user.messages.build(message_params)
    if message.save
      redirect_to root_path
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [:new, :create]

  def new

  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = ["Success", "You've successfully logged in"]
      redirect_to root_path
    else
      flash.now[:error] = ["There was a problem", "Your username and/or password are incorrect"]
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = ["We hope to see you soon!", "You've successfully logged out"]
    redirect_to login_path
  end

  private

  def logged_in_redirect
    if logged_in?
      flash[:warning] = ["You are already logged in"]
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/chatrooms/index.html.erb
<h3 class="ui center aligned icon header">
  <i class="big comments outline icon"></i>
  Let's talk!
</h3>
<div class="ui two column grid">
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui feed">
          <%= render @messages %>
        </div>
      </div>
      <div class="extra content">
        <%= form_for(@message, html: {class: "ui reply form", role: "form"}, url: message_path) do |f| %>
          <div class="field">
            <div class="ui fluid icon input">
              <%= f.text_field :body, placeholder: 'Enter your message...' %>
              <%= f.button '<i class="icon edit message"></i>'.html_safe %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui vertical menu">
          <%= render @users %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, content| %>
  <div class="ui <%= type %> message transition">
    <i class="close icon"></i>
    <div class="header">
      <%= content[0] %>
    </div>
    <% if content.length > 1 %>
      <p><%= content[1] %></p>
    <% end %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="item">
  <i class="big comments outline icon"></i>
</div>
<%= link_to "Chatroom", root_path, :class => "item" %>
<a class="item">
  Messages
</a>
<div class="right menu">
  <div class="ui dropdown item">
    Account <i class="dropdown icon"></i>
    <div class="menu">
      <% if logged_in? %>
        <%= link_to "Log out", logout_path, method: :delete, :class => "item" %>
      <% else %>
        <%= link_to "Log in", login_path, :class => "item" %>
        <a class="item">Sign up</a>
      <% end %>
    </div>
  </div>
  <div class="item">
    <% if !logged_in? %>
      <div class="ui primary button">Sign Up</div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui small menu">
      <div class="ui container">
        <%= render "layouts/navigation" %>
      </div>
    </div>
    <div class="ui container">
      <%= render "layouts/flash_messages" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
       <em>[<%= time_ago_in_words(message.created_at) %> ago] - <%= message.user.username %>: </em>
       <span class="message"><%= message.body %><span>
    </div>
  </div>
</div>

app/views/users/_user.html.erb
<a class="active item">
  <%= user.username %>
</a>